from django.conf.urls import  patterns, include, url 

urlpatterns = patterns('',
	url(r'^home/$','mymusic.views.home'),
	url(r'^signup/$','mymusic.views.signup'),
	url(r'^signin/$','mymusic.views.signin'),
	url(r'^auth/$', 'mymusic.views.auth_view'),
	url(r'^logged/$', 'mymusic.views.home'),
	url(r'^admin_auth/$', 'mymusic.views.admin_auth'),
	url(r'^adminpage/$', 'mymusic.views.admin_logged_in'),
	url(r'^adminlogin/$','mymusic.views.adminlogin'),
	url(r'^create/$', 'mymusic.views.create'),
	url(r'^uploadsong/$','mymusic.views.create'),
	url(r'^search/$', 'mymusic.views.search'),
	url(r'^play/(?P<song_id>\d+)/$', 'mymusic.views.playsong'),
	url(r'^logout/$','mymusic.views.logout'),
	url(r'^playlist/$', 'mymusic.views.playlist'),
	url(r'^addtolist/(?P<song_id>\d+)/$','mymusic.views.addtolist'),
	url(r'^search/(telugu|hindi|english|tamil|malayalam)/$','mymusic.views.searchLang'),
	url(r'^delitem/(?P<song_id>\d+)/$','mymusic.views.delitem'),
	)